---
apiVersion: v1
kind: Secret
metadata:
  name: app-service1-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/janus-backstage/app-service1-gitops.git
